name = "test_project"
profile = "default"
file_path = "./projects/test_project.toml"

[[sections]]
bpm = 180
measures = 4

[sections.time_signature]
beats_per_bar = 4
beat_unit = 4

[[sections]]
bpm = 120
measures = 2

[sections.time_signature]
beats_per_bar = 4
beat_unit = 4

[[sections]]
bpm = 80
measures = 4

[sections.time_signature]
beats_per_bar = 4
beat_unit = 4
